---
ID: "3681b6ea-237b-4bb9-a57d-20207e0a7f8d"
Parent: "9ded1ed4-9da0-475e-a166-6d52cce47b99"
Template: "9ded1ed4-9da0-475e-a166-6d52cce47b99"
Path: /sitecore/templates/Project/SUGLATAM/Workshop/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240208T020135Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5200c3dc-fd86-4774-9e9f-64b2e7f9e099"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240208T020135Z
