---
ID: "078e48cd-4664-4ca7-9cd3-587ec24f3463"
Parent: "5e93d5a4-ecf7-49bd-8ffc-3234e3419271"
Template: "5e93d5a4-ecf7-49bd-8ffc-3234e3419271"
Path: /sitecore/templates/Feature/SUGLATAM/Doctors/Rendering Parameters/Doctors Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240425T030315Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "14df22bb-262f-4249-b476-0a6ee1b740eb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240502T032505Z
