---
ID: "9dab004e-664f-4ab4-8fc2-e2deff456fc3"
Parent: "af604b42-09e4-4bd3-8176-76870c70f44c"
Template: "af604b42-09e4-4bd3-8176-76870c70f44c"
Path: /sitecore/templates/Feature/SUGLATAM/Page Content/Rendering Parameters/Page Content Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240425T030315Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "485560ea-8a02-4eb0-9e78-f838d5aafab7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240425T030315Z
